version: '3.9'
services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=victhun
      - POSTGRES_PASSWORD=zzzewre4g3a!
      - POSTGRES_DB=nefu
volumes:
  postgresql: