import { type NextPage } from "next";
import Head from "next/head";
import Schedule from "~/components/schedule";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.schedule.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Victhub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data ? <Schedule data={data} /> : ""}
    </>
  );
};

export default Home;
